name: function

on: 
  workflow_run: 
    workflows: [CI]
    types:
      - completed

jobs:
  # This workflow contains a single job called "build"
  Dev:
    name: dev
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
        - name: print hello
          run: echo hello
        
    
